spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot_test?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123



mybatis:
  type-aliases-package: cn.linguolai.springdemo.bean
  mapper-locations: classpath*:mappers/*.xml

